Do not apply mandatory-files policy to openjdk sources
microsoft/.github pull request #160
Opened 2023-06-08 21:49 UTC by d3r3kk

Our workflow requires that we mirror the upstream OpenJDK sources from their `master` branch to our `main` branch without any divergence. We then apply open-source Microsoft driven patches to a release branch, based off that mirrored `main` to build our binaries with.

We'd like to avoid diverging our `main` branch at all.

2023-06-08 22:00 UTC, joe-braley reviewed
Looks fine though I do have one question.

2023-06-08 22:39 UTC, jeffwilcox requested changes
this is blocked by an underlying deployment that is pending on the policy system to evaluate this correctly

2023-06-09 19:37 UTC, d3r3kk commented on policies/mandatory-files.yml
> +  ||!repository.name.equals("openjdk-jdk11", StringComparison.InvariantCultureIgnoreCase)
Yes, caught that just after my submission - looks right now (I think).

2023-06-12 17:49 UTC, DragosDanielBoia approved these changes

2023-06-12 18:19 UTC, jeffwilcox approved these changes

2023-06-12 18:29 UTC, merged

2023-06-12 20:19 UTC, d3r3kk commented on policies/mandatory-files.yml
> +  ||!repository.name.equals("openjdk-jdk11u", StringComparison.InvariantCultureIgnoreCase)
Thanks for taking care of this for us!